// <auto-generated />
using System;
using HK_Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HK_Database.Migrations
{
    [DbContext(typeof(HKContext))]
    [Migration("20230613032908_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HK_Database.Models.Applications", b =>
                {
                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("MemberId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            ApplicationId = "A001",
                            MemberId = "C001",
                            Model = "mm"
                        },
                        new
                        {
                            ApplicationId = "A002",
                            MemberId = "C002",
                            Model = "mm"
                        });
                });

            modelBuilder.Entity("HK_Database.Models.Chats", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChatData")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            ChatId = "C001",
                            ChatData = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(13),
                            ChatName = "Gay",
                            UserId = "U001"
                        });
                });

            modelBuilder.Entity("HK_Database.Models.Datas", b =>
                {
                    b.Property<string>("DataId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Datas");

                    b.HasData(
                        new
                        {
                            DataId = "D001",
                            ApplicationId = "A001",
                            DataPath = "dd",
                            DataType = "dd"
                        },
                        new
                        {
                            DataId = "D002",
                            ApplicationId = "A002",
                            DataPath = "dd",
                            DataType = "dd"
                        });
                });

            modelBuilder.Entity("HK_Database.Models.Embedding", b =>
                {
                    b.Property<string>("Index")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmbeddingAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingVectors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Index");

                    b.HasIndex("DataId");

                    b.ToTable("Embedding");

                    b.HasData(
                        new
                        {
                            Index = "ii",
                            DataId = "D001",
                            EmbeddingAnswer = "ee",
                            EmbeddingQuestion = "ee",
                            EmbeddingVectors = "ee",
                            QA = "qq"
                        });
                });

            modelBuilder.Entity("HK_Database.Models.Member", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("APIKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            MemberId = "C001",
                            APIKey = "aa",
                            MemberAccount = "althea",
                            MemberEmail = "althea@gmail.com",
                            MemberName = "Althea",
                            MemberPassword = "althea01",
                            MemberPhone = "0912345678"
                        },
                        new
                        {
                            MemberId = "C002",
                            APIKey = "aa",
                            MemberAccount = "jimmy",
                            MemberEmail = "jimmy@gmail.com",
                            MemberName = "Jimmy",
                            MemberPassword = "jimmy02",
                            MemberPhone = "0944332211"
                        });
                });

            modelBuilder.Entity("HK_Database.Models.QAHistory", b =>
                {
                    b.Property<string>("QAHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QAHistoryA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QAHistoryQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QAHistoryVectors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QAHistoryId");

                    b.HasIndex("ChatId");

                    b.ToTable("QAHistory");

                    b.HasData(
                        new
                        {
                            QAHistoryId = "Q001",
                            ChatId = "C001",
                            QAHistoryA = "qq",
                            QAHistoryQ = "qq",
                            QAHistoryVectors = "qq"
                        });
                });

            modelBuilder.Entity("HK_Database.Models.Users", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "U001",
                            ApplicationId = "A001",
                            UserAccount = "candy",
                            UserEmail = "candy@gmail.com",
                            UserName = "Candy",
                            UserPassword = "candy03",
                            UserPhone = "0987654654"
                        });
                });

            modelBuilder.Entity("HK_Database.Models.Applications", b =>
                {
                    b.HasOne("HK_Database.Models.Member", "Member")
                        .WithMany("Applications")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HK_Database.Models.Chats", b =>
                {
                    b.HasOne("HK_Database.Models.Users", "Users")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HK_Database.Models.Datas", b =>
                {
                    b.HasOne("HK_Database.Models.Applications", "Applications")
                        .WithMany("Datas")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applications");
                });

            modelBuilder.Entity("HK_Database.Models.Embedding", b =>
                {
                    b.HasOne("HK_Database.Models.Datas", "Datas")
                        .WithMany("Embedding")
                        .HasForeignKey("DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datas");
                });

            modelBuilder.Entity("HK_Database.Models.QAHistory", b =>
                {
                    b.HasOne("HK_Database.Models.Chats", "Chats")
                        .WithMany("QAHistory")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chats");
                });

            modelBuilder.Entity("HK_Database.Models.Users", b =>
                {
                    b.HasOne("HK_Database.Models.Applications", "Applications")
                        .WithMany("Users")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applications");
                });

            modelBuilder.Entity("HK_Database.Models.Applications", b =>
                {
                    b.Navigation("Datas");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HK_Database.Models.Chats", b =>
                {
                    b.Navigation("QAHistory");
                });

            modelBuilder.Entity("HK_Database.Models.Datas", b =>
                {
                    b.Navigation("Embedding");
                });

            modelBuilder.Entity("HK_Database.Models.Member", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("HK_Database.Models.Users", b =>
                {
                    b.Navigation("Chats");
                });
#pragma warning restore 612, 618
        }
    }
}
